// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PayrollBackendProject.Infrastructure.Data;

#nullable disable

namespace PayrollBackendProject.Migrations
{
    [DbContext(typeof(ClinicianDbContext))]
    [Migration("20260402110653_UpdateGuidInUserToNullAgain")]
    partial class UpdateGuidInUserToNullAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.Clinician", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("CostShare")
                        .HasColumnType("double precision");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasPsychToday")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clinicians");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.EHRUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClinicianID")
                        .HasColumnType("uuid");

                    b.Property<string>("EHRUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianID");

                    b.HasIndex("UserAccountId");

                    b.ToTable("EHRUsers");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailedItems")
                        .HasColumnType("integer");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StatusTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PayRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ApprovedRejectedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedRejectedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GenerationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StatementTotals")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAdjudicated")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalApplied")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PayRuns");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PayStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalState")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ApprovedRejectedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedRejectedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ClinicianCostShare")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ClinicianId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostShareAdjustedPayment")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PayRunId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAdjustment")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId");

                    b.HasIndex("PayRunId");

                    b.ToTable("PayStatements");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PayStatementLineItem", b =>
                {
                    b.Property<Guid>("PaymentLineItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PayStatementId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustmentAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.HasKey("PaymentLineItemId", "PayStatementId");

                    b.HasIndex("PayStatementId");

                    b.ToTable("PayStatementLineItem");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PaymentLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdjustmentAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("AdjustmentCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("AppliedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CPTCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClinicianId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfService")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PayRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rowNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppliedById");

                    b.HasIndex("ClinicianId");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("PayRunId");

                    b.ToTable("PaymentLineItems");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClinicianId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PracticeMateAccountName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClinicianId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.EHRUser", b =>
                {
                    b.HasOne("PayrollBackendProject.Domain.Entity.Clinician", "Clinician")
                        .WithMany()
                        .HasForeignKey("ClinicianID");

                    b.HasOne("PayrollBackendProject.Domain.Entity.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId");

                    b.Navigation("Clinician");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PayStatement", b =>
                {
                    b.HasOne("PayrollBackendProject.Domain.Entity.Clinician", "Clinician")
                        .WithMany()
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollBackendProject.Domain.Entity.PayRun", "PayRun")
                        .WithMany("Statements")
                        .HasForeignKey("PayRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinician");

                    b.Navigation("PayRun");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PayStatementLineItem", b =>
                {
                    b.HasOne("PayrollBackendProject.Domain.Entity.PayStatement", "PayStatement")
                        .WithMany("LineItems")
                        .HasForeignKey("PayStatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollBackendProject.Domain.Entity.PaymentLineItem", "PaymentLineItem")
                        .WithMany("PayStatementLineItems")
                        .HasForeignKey("PaymentLineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PayStatement");

                    b.Navigation("PaymentLineItem");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PaymentLineItem", b =>
                {
                    b.HasOne("PayrollBackendProject.Domain.Entity.EHRUser", "AppliedBy")
                        .WithMany()
                        .HasForeignKey("AppliedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollBackendProject.Domain.Entity.Clinician", "Clinician")
                        .WithMany()
                        .HasForeignKey("ClinicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollBackendProject.Domain.Entity.ImportBatch", "ImportBatch")
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PayrollBackendProject.Domain.Entity.PayRun", null)
                        .WithMany("Payments")
                        .HasForeignKey("PayRunId");

                    b.Navigation("AppliedBy");

                    b.Navigation("Clinician");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.UserAccount", b =>
                {
                    b.HasOne("PayrollBackendProject.Domain.Entity.Clinician", "Clinician")
                        .WithMany()
                        .HasForeignKey("ClinicianId");

                    b.Navigation("Clinician");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PayRun", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Statements");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PayStatement", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("PayrollBackendProject.Domain.Entity.PaymentLineItem", b =>
                {
                    b.Navigation("PayStatementLineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
