name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ "main" ]
  
env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/payroll-api

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
    
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

  docker:
    name: Docker
    needs: build-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Build Docker image
      run: docker build -t $IMAGE_NAME:latest -f PayrollBackendProject.API/Dockerfile .
    
    - name: Push Docker image
      run: docker push $IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy docker image
      run: curl -X POST ${{ secrets.DEPLOY_HOOK }}
